### PR TITLE
Fix default value of `methods` in `_try_all` to avoid exception

### PR DESCRIPTION
**Pull request by sciunto**
## Description

I discovered a trivial bug if method is used with the default value. len(None) will throw a TypeError. The bug was introduced by myself. However, it's not critical. The function is private.

### CODE REVIEW

**Comment by jni** [comment]
Erm, this doesn't actually fix the issue? :joy: `AttributeError: 'tuple' object has no attribute 'items'`. Since the input type is dict, I suggest either `dict()` or `None` with a line: `methods = methods or {}` inside the function. The second line is slightly preferable because it's considered bad practice to use mutable objects as default values.

**Comment by sciunto** [comment]
argh, I read tuple instead of dict :(

**Comment by sciunto** [comment]
Fixed. Thanks @jni for the hint.

File: skimage/filters/thresholding.py [hunk 1]
```diff
@@ -47,6 +47,9 @@ def _try_all(image, methods=None, figsize=None, num_cols=2, verbose=True):
     """
     from matplotlib import pyplot as plt
 
+    # Handle default value
+    methods = methods or {}
```
Comment (hmaarrfk) [inline skimage/filters/thresholding.py]: I'm just going to say that I really don't like this line of logic. I get that `None is Flasy`, but man, is a `dictionary Truthy`?

I would much prefer
```
methods = {} if methods is None else method
```
or 
```
if methods is None:
    methods = {}
```

Comment (jni) [reply skimage/filters/thresholding.py]: @hmaarrfk the dictionary doesn't have to be truthy. (In fact it isn't: empty collections are `False`.) I only learned of this expression quite recently but I very much like it as a concise way of representing your alternatives. To me it reads quite naturally. Having said that I get the objection and will not myself object if others prefer one of your more explicit forms.

Comment (hmaarrfk) [reply skimage/filters/thresholding.py]: my issue with that particular line is that it has no equivalence in many other languages. Typically the result of an or expression is a Boolean, but now it is either the LHS or the RHS.


False, empty lists, empty tuples, zero are not valid inputs to this function and that line of logic might imply so in 4 years.

Comment (jni) [reply skimage/filters/thresholding.py]: But that's fine: all of the above inputs would cause a nasty `AttributeError` later on in the function with your alternative syntax, so I don't find them to be compelling reasons not to use this...
