### ISSUE TITLE
Pillow>7.0.0 PngImageFile object has no attribute '_PngImageFile_frame'

### ISSUE THREAD

**Issue by FRUEHNI1** [scikit-image/scikit-image#4548]
## Description
Works with Pillow==7.0.0, not working with Pillow==7.1.0

```python
img = imread("anyimage.png")
```

```
test/test_image_preprocess.py:7: in <module>
    img = imread("examples/data/test.png")
/usr/local/lib/python3.7/site-packages/skimage/io/_io.py:48: in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
/usr/local/lib/python3.7/site-packages/skimage/io/manage_plugins.py:210: in call_plugin
    return func(*args, **kwargs)
/usr/local/lib/python3.7/site-packages/skimage/io/_plugins/imageio_plugin.py:10: in imread
    return np.asarray(imageio_imread(*args, **kwargs))
/usr/local/lib/python3.7/site-packages/imageio/core/functions.py:223: in imread
    return reader.get_data(0)
/usr/local/lib/python3.7/site-packages/imageio/core/format.py:339: in get_data
    im, meta = self._get_data(index, **kwargs)
/usr/local/lib/python3.7/site-packages/imageio/plugins/pillow.py:296: in _get_data
    im, info = PillowFormat.Reader._get_data(self, index)
/usr/local/lib/python3.7/site-packages/imageio/plugins/pillow.py:172: in _get_data
    i = self._im.tell()
/usr/local/lib/python3.7/site-packages/PIL/PngImagePlugin.py:827: in tell
    return self.__frame
E   AttributeError: 'PngImageFile' object has no attribute '_PngImageFile__frame'
```

**Comment by hmaarrfk** [comment]
from the stack trace, this seems like a PIL issue, but I can't be sure.

**Comment by hmaarrfk** [comment]
can you read a PNG directly with PIL or imageio?

**Comment by hugovk** [comment]
This was a problem in Pillow 7.1.0, fixed in 7.1.1. Please could you upgrade and try again?

https://github.com/python-pillow/Pillow/issues/4509

**Comment by sciunto** [comment]
Thanks @hugovk ! It solves the issue on my side. I'm closing this issue. If some still have the issue after update, please, reopen.
