### ISSUE TITLE
Failure to install pyamg on Py 2.7 causing Travis failures

### ISSUE THREAD

**Issue by jni** [scikit-image/scikit-image#1788]
See eg [here](https://travis-ci.org/scikit-image/scikit-image/jobs/91212428#L3815).

```
pip install --retries 3 -q pyamg
Command "/home/travis/venv/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-U7eYqA/pyamg/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-xL9shZ-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/travis/venv/include/site/python2.7/pyamg" failed with error code 1 in /tmp/pip-build-U7eYqA/pyamg
The command "tools/travis_script.sh" exited with 1.
```

**Comment by jni** [comment]
@JDWarner @emmanuelle I believe you guys were the pyamg "experts"? (Correct me if I'm wrong.) Any idea what's going on here?

**Comment by Hiyorimi** [comment]
I stack on the same error for python 2.7 and created a question @ [StackOverflow!] (http://stackoverflow.com/questions/34103531/python-scikit-image-pull-request-travis-ci-python-2-7-build-fails)

**Comment by Hiyorimi** [comment]
@jni can you upvote [question](http://stackoverflow.com/questions/34103531/python-scikit-image-pull-request-travis-ci-python-2-7-build-fails?noredirect=1#comment55958641_34103531) at StackOverflow, so it will have better chance to attract someones attention

**Comment by JDWarner** [comment]
I turned off the `-q` option in a personal Travis build; perhaps this will assist in figuring out the problem for the pyamg folks.

The [full log is here](https://travis-ci.org/JDWarner/scikit-image/jobs/95088900), copied below:

```
+pip install --retries 3 pyamg
Collecting pyamg
  Downloading pyamg-3.0.1.tar.gz (759kB)
    100% |████████████████████████████████| 761kB 718kB/s 
Building wheels for collected packages: pyamg
  Running setup.py bdist_wheel for pyamg
  Complete output from command /home/travis/venv/bin/python -c "import setuptools;__file__='/tmp/pip-build-_TPeac/pyamg/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpsi3gXIpip-wheel-:
  Running from pyamg source directory.
  running bdist_wheel
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  build_src
  building py_modules sources
  building extension "pyamg.amg_core._amg_core" sources
  building data_files sources
  build_src: building npy-pkg config files
  running build_py
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/pyamg
  copying pyamg/__init__.py -> build/lib.linux-x86_64-2.7/pyamg
  copying pyamg/blackbox.py -> build/lib.linux-x86_64-2.7/pyamg
  copying pyamg/graph.py -> build/lib.linux-x86_64-2.7/pyamg
  copying pyamg/info.py -> build/lib.linux-x86_64-2.7/pyamg
  copying pyamg/multilevel.py -> build/lib.linux-x86_64-2.7/pyamg
  copying pyamg/setup.py -> build/lib.linux-x86_64-2.7/pyamg
  copying pyamg/strength.py -> build/lib.linux-x86_64-2.7/pyamg
  copying pyamg/version.py -> build/lib.linux-x86_64-2.7/pyamg
  copying build/src.linux-x86_64-2.7/pyamg/__config__.py -> build/lib.linux-x86_64-2.7/pyamg
  creating build/lib.linux-x86_64-2.7/pyamg/aggregation
  copying pyamg/aggregation/__init__.py -> build/lib.linux-x86_64-2.7/pyamg/aggregation
  copying pyamg/aggregation/adaptive.py -> build/lib.linux-x86_64-2.7/pyamg/aggregation
  copying pyamg/aggregation/aggregate.py -> build/lib.linux-x86_64-2.7/pyamg/aggregation
  copying pyamg/aggregation/aggregation.py -> build/lib.linux-x86_64-2.7/pyamg/aggregation
  copying pyamg/aggregation/rootnode.py -> build/lib.linux-x86_64-2.7/pyamg/aggregation
  copying pyamg/aggregation/setup.py -> build/lib.linux-x86_64-2.7/pyamg/aggregation
  copying pyamg/aggregation/smooth.py -> build/lib.linux-x86_64-2.7/pyamg/aggregation
  copying pyamg/aggregation/tentative.py -> build/lib.linux-x86_64-2.7/pyamg/aggregation
  creating build/lib.linux-x86_64-2.7/pyamg/classical
  copying pyamg/classical/__init__.py -> build/lib.linux-x86_64-2.7/pyamg/classical
  copying pyamg/classical/classical.py -> build/lib.linux-x86_64-2.7/pyamg/classical
  copying pyamg/classical/cr.py -> build/lib.linux-x86_64-2.7/pyamg/classical
  copying pyamg/classical/interpolate.py -> build/lib.linux-x86_64-2.7/pyamg/classical
  copying pyamg/classical/setup.py -> build/lib.linux-x86_64-2.7/pyamg/classical
  copying pyamg/classical/split.py -> build/lib.linux-x86_64-2.7/pyamg/classical
  creating build/lib.linux-x86_64-2.7/pyamg/gallery
  copying pyamg/gallery/__init__.py -> build/lib.linux-x86_64-2.7/pyamg/gallery
  copying pyamg/gallery/demo.py -> build/lib.linux-x86_64-2.7/pyamg/gallery
  copying pyamg/gallery/diffusion.py -> build/lib.linux-x86_64-2.7/pyamg/gallery
  copying pyamg/gallery/elasticity.py -> build/lib.linux-x86_64-2.7/pyamg/gallery
  copying pyamg/gallery/example.py -> build/lib.linux-x86_64-2.7/pyamg/gallery
  copying pyamg/gallery/info.py -> build/lib.linux-x86_64-2.7/pyamg/gallery
  copying pyamg/gallery/laplacian.py -> build/lib.linux-x86_64-2.7/pyamg/gallery
  copying pyamg/gallery/mesh.py -> build/lib.linux-x86_64-2.7/pyamg/gallery
  copying pyamg/gallery/random_sparse.py -> build/lib.linux-x86_64-2.7/pyamg/gallery
  copying pyamg/gallery/setup.py -> build/lib.linux-x86_64-2.7/pyamg/gallery
  copying pyamg/gallery/stencil.py -> build/lib.linux-x86_64-2.7/pyamg/gallery
  creating build/lib.linux-x86_64-2.7/pyamg/krylov
  copying pyamg/krylov/__init__.py -> build/lib.linux-x86_64-2.7/pyamg/krylov
  copying pyamg/krylov/_bicgstab.py -> build/lib.linux-x86_64-2.7/pyamg/krylov
  copying pyamg/krylov/_cg.py -> build/lib.linux-x86_64-2.7/pyamg/krylov
  copying pyamg/krylov/_cgne.py -> build/lib.linux-x86_64-2.7/pyamg/krylov
  copying pyamg/krylov/_cgnr.py -> build/lib.linux-x86_64-2.7/pyamg/krylov
  copying pyamg/krylov/_cr.py -> build/lib.linux-x86_64-2.7/pyamg/krylov
  copying pyamg/krylov/_fgmres.py -> build/lib.linux-x86_64-2.7/pyamg/krylov
  copying pyamg/krylov/_gmres.py -> build/lib.linux-x86_64-2.7/pyamg/krylov
  copying pyamg/krylov/_gmres_householder.py -> build/lib.linux-x86_64-2.7/pyamg/krylov
  copying pyamg/krylov/_gmres_mgs.py -> build/lib.linux-x86_64-2.7/pyamg/krylov
  copying pyamg/krylov/_minimal_residual.py -> build/lib.linux-x86_64-2.7/pyamg/krylov
  copying pyamg/krylov/_steepest_descent.py -> build/lib.linux-x86_64-2.7/pyamg/krylov
  copying pyamg/krylov/info.py -> build/lib.linux-x86_64-2.7/pyamg/krylov
  copying pyamg/krylov/setup.py -> build/lib.linux-x86_64-2.7/pyamg/krylov
  creating build/lib.linux-x86_64-2.7/pyamg/amg_core
  copying pyamg/amg_core/__init__.py -> build/lib.linux-x86_64-2.7/pyamg/amg_core
  copying pyamg/amg_core/amg_core.py -> build/lib.linux-x86_64-2.7/pyamg/amg_core
  copying pyamg/amg_core/setup.py -> build/lib.linux-x86_64-2.7/pyamg/amg_core
  creating build/lib.linux-x86_64-2.7/pyamg/relaxation
  copying pyamg/relaxation/__init__.py -> build/lib.linux-x86_64-2.7/pyamg/relaxation
  copying pyamg/relaxation/chebyshev.py -> build/lib.linux-x86_64-2.7/pyamg/relaxation
  copying pyamg/relaxation/info.py -> build/lib.linux-x86_64-2.7/pyamg/relaxation
  copying pyamg/relaxation/relaxation.py -> build/lib.linux-x86_64-2.7/pyamg/relaxation
  copying pyamg/relaxation/setup.py -> build/lib.linux-x86_64-2.7/pyamg/relaxation
  copying pyamg/relaxation/smoothing.py -> build/lib.linux-x86_64-2.7/pyamg/relaxation
  creating build/lib.linux-x86_64-2.7/pyamg/testing
  copying pyamg/testing/__init__.py -> build/lib.linux-x86_64-2.7/pyamg/testing
  creating build/lib.linux-x86_64-2.7/pyamg/util
  copying pyamg/util/__init__.py -> build/lib.linux-x86_64-2.7/pyamg/util
  copying pyamg/util/BSR_utils.py -> build/lib.linux-x86_64-2.7/pyamg/util
  copying pyamg/util/info.py -> build/lib.linux-x86_64-2.7/pyamg/util
  copying pyamg/util/linalg.py -> build/lib.linux-x86_64-2.7/pyamg/util
  copying pyamg/util/setup.py -> build/lib.linux-x86_64-2.7/pyamg/util
  copying pyamg/util/utils.py -> build/lib.linux-x86_64-2.7/pyamg/util
  creating build/lib.linux-x86_64-2.7/pyamg/vis
  copying pyamg/vis/__init__.py -> build/lib.linux-x86_64-2.7/pyamg/vis
  copying pyamg/vis/info.py -> build/lib.linux-x86_64-2.7/pyamg/vis
  copying pyamg/vis/setup.py -> build/lib.linux-x86_64-2.7/pyamg/vis
  copying pyamg/vis/vis_coarse.py -> build/lib.linux-x86_64-2.7/pyamg/vis
  copying pyamg/vis/vtk_writer.py -> build/lib.linux-x86_64-2.7/pyamg/vis
  running build_ext
  customize UnixCCompiler
  customize UnixCCompiler using build_ext
  customize UnixCCompiler
  customize UnixCCompiler using build_ext
  building 'pyamg.amg_core._amg_core' extension
  compiling C++ sources
  C compiler: g++ -pthread -fno-strict-aliasing -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -O3 -Wall -fPIC
  
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/pyamg
  creating build/temp.linux-x86_64-2.7/pyamg/amg_core
  compile options: '-D__STDC_FORMAT_MACROS=1 -I/home/travis/venv/lib/python2.7/site-packages/numpy/core/include -I/opt/python/2.7.9/include/python2.7 -c'
  g++: pyamg/amg_core/amg_core_wrap.cxx
  pyamg/amg_core/amg_core_wrap.cxx: In function ‘PyArrayObject* make_fortran(PyArrayObject*, int*)’:
  pyamg/amg_core/amg_core_wrap.cxx:3596:51: error: ‘NPY_ARRAY_F_CONTIGUOUS’ was not declared in this scope
  pyamg/amg_core/amg_core_wrap.cxx: In function ‘PyArrayObject* make_fortran(PyArrayObject*, int*)’:
  pyamg/amg_core/amg_core_wrap.cxx:3596:51: error: ‘NPY_ARRAY_F_CONTIGUOUS’ was not declared in this scope
  error: Command "g++ -pthread -fno-strict-aliasing -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -D__STDC_FORMAT_MACROS=1 -I/home/travis/venv/lib/python2.7/site-packages/numpy/core/include -I/opt/python/2.7.9/include/python2.7 -c pyamg/amg_core/amg_core_wrap.cxx -o build/temp.linux-x86_64-2.7/pyamg/amg_core/amg_core_wrap.o" failed with exit status 1
```

**Comment by lukeolson** [comment]
I'll take a look at this from the pyamg end...

**Comment by JDWarner** [comment]
Much appreciated, @lukeolson!

**Comment by jni** [comment]
@JDWarner based on the answer on SO, perhaps we should pin pyamg to 2.x? This is kind of the point of semantic versioning... One should not in general expect a library written for version n.x to work with (n+1).y.

**Comment by JDWarner** [comment]
@jni I disagree with that answer but can't comment yet on StackOverflow. Throwing up our hands and pinning an old version is very unsatisfactory. pyamg is far from an abandoned library and it builds for the official project on Travis. I raised an issue over there too; let's give it a little time.

**Comment by lukeolson** [comment]
@jni @JDWarner yep I'd like to work with you to get this resolved from the pyamg end.  The pyamg builds on 2.6 -- 3.5, but does so with the miniconda setup.

Any idea on which version of numpy + scipy versions the build is failing on?  This could be an old numpy issue.

**Comment by jni** [comment]
@lukeolson great to hear, thank you! =)

The 2.7 build uses the minimal requirements, which are listed [here](https://github.com/scikit-image/scikit-image/blob/master/DEPENDS.txt). (Though we are talking about bumping the Pillow line to 2.1).

Specifically, NumPy=1.6.1, SciPy=0.9.

**Comment by emmanuelle** [comment]
@lukeolson on a slightly different topic, pyamg is an optional dependency because we use ``ruge_stuben_solver`` in random walker segmentation (and it works great, thanks a lot!). That's the only function from pyamg that we use. How much work do you estimate would be required to take some code from pyamg into a self-contained module if we wanted to remove this dependency? I had a quick look a while ago, and it seemed that quite a lot of code from the package was called from ``ruge_stuben_solver``, therefore it seemed reasonable to me to keep the dependency, but I'd like to hear your opinion. 

And many thanks for your help on this issue!

**Comment by blink1073** [comment]
We could instead bump our minimum versions of numpy and scipy.

**Comment by stefanv** [comment]
Shall we disable the pyamg installation & test for now?  This is holding back development.

**Comment by blink1073** [comment]
I'd say just disable it on the Python 2.7 Travis build, and add a issue to track it.

**Comment by blink1073** [comment]
(Or just leave this one open).

**Comment by lukeolson** [comment]
As far as I can tell it fails only with with `numpy==1.6.1` and `scipy=0.9`.

So the options as the moment are to raise the version requirements as @blink1073 suggests, or hold off on pyamg 3.0 until we can get this figured out.

**Comment by lukeolson** [comment]
I have just pushed a fix here: https://github.com/pyamg/pyamg/commit/fd7463df13553d0aa282741eb756efba76d6d1b5

on another note, it appears that pandas is dropping np 1.6 support:
pydata/pandas#7711
so it may be time here too

I'll work on getting a new pyamg dist to pypi

**Comment by lukeolson** [comment]
@stefanv, pyamg 3.0.2 is now live and fixes this issue.  Tests pass on my end, but let me know if you see issues.

**Comment by stefanv** [comment]
Fantastic, thank you Luke!
