### ISSUE TITLE
build fails with Python 3.3.3 on Win7 x64 with VS2010

### ISSUE THREAD

**Issue by jrminter** [scikit-image/scikit-image#867]
I have a successful build on this Win 7 x64 system from 2014-01-20. I just tried to do a build using python 3.3.3 x64 from the current pull:

> $ git whatchanged
> commit ee3ca829c6e9ec55a444d2c15ab538c548312976
> Author: Michal Romaniuk michal.romaniuk06@ic.ac.uk
> Date:   Sun Jan 26 18:01:59 2014 +0000

The build fails with a link error complaining about not being able to find "round"

> Creating library build\temp.win-amd64-3.3\Release\skimage\feature\orb_cy.lib and
> object build\temp.win-amd64-3.3\Release\skimage\feature\orb_cy.exp orb_cy.obj :
> error LNK2019: unresolved external symbol round referenced in function 
> __pyx_pf_7skimage_7feature_6orb_cy__orb_loop

This looks like a libc issue, because looking at orb_cy.pyx I see:

> from libc.math cimport sin, cos, round

Since  VS2010 is the compiler for Python 3.3.X on Windows. I was hoping someone had seen this before and can help me fix this.

Thanks,
John
