### ISSUE TITLE
ImportError: cannot import name 'img_as_float32'

### ISSUE THREAD

**Issue by trihesdlin** [scikit-image/scikit-image#3874]
## Version information
```python
print(np.__version__)
print(skimage.__version__)
```

```python
1.16.3
0.13.1
```
## The error info is:
```python
/anaconda3/lib/python3.6/site-packages/skimage/util/__init__.py in <module>()
----> 1 from .dtype import (img_as_float32, img_as_float64, img_as_float,
      2                     img_as_int, img_as_uint, img_as_ubyte,
      3                     img_as_bool, dtype_limits)
      4 from .shape import view_as_blocks, view_as_windows
      5 from .noise import random_noise

ImportError: cannot import name 'img_as_float32'
```
I've updated the numpy and skimage to the latest version and still got the error. I do not know what to do. Can anyone help me?

**Comment by trihesdlin** [comment]
I just reopened the file. And it works.

**Comment by hmaarrfk** [comment]
Glad things worked out1

scikit image 0.13 is pretty old. Typically I wouldn't say anything, but the fact that you are running numpy 1.16 + scikit-image 0.13 is strane.

Consider updating to 0.14.2

I know for a fact that 0.14.1 doesn't work with numpy 1.16 so be sure to skip that one.

Happy processing!
