### PR TITLE
Lazily load data_dir into the top-level namespace

### PR DESCRIPTION
**Pull request by grlee77**
## Description

This is a follow up PR to #5101 that delays loading of `skimage.data_dir`. Currently, importing that in the top-level `__init__.py` results in importing Pooch. With the change here, `data_dir` is lazily loaded.

The diff here is much smaller than it appears because all code in `_fetchers.py` is just the old `__init__.py`. Aside from removing `__all__` after the rename, I made only a 1 line change to fix an issue with parsing the modified `__version__` string containing the git hash introduced in #5909.

This PR also fixes an issue where `skimage.data.vortex` was missing from `skimage.data.__all__`.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

### CODE REVIEW

**Comment by grlee77** [comment]
This lazy loading should also help resolve #5146 (at least the error would not occur upon the top-level import). I will add another commit here to deal with the issue of missing `pooch.__version__` on older Pooch (as reported in https://github.com/scikit-image/scikit-image/issues/5146#issuecomment-782748290)

**Comment by grlee77** [comment]
I manually verified that 26a580e avoids the problem with `AttributeError: module 'pooch' has no attribute '__version__'` with Pooch 1.1.0 since we do not run CI tests with that version.

**Comment by grlee77** [comment]
closes #5146

**Review by stefanv — APPROVED** [review]

**Review by alexdesiqueira — APPROVED** [review]

**Comment by alexdesiqueira** [comment]
Thank you @grlee77!
