### ISSUE TITLE
ImportError for `skimage.transform.resize` when using `PYTHONOPTIMIZE=2` on python3.13

### ISSUE THREAD

**Issue by ancestor-mithril** [scikit-image/scikit-image#8089]
### Description:

Importing `resize` from `skimage.transform` fails when using `PYTHONOPTIMIZE=2` on python3.13. 
It works with `PYTHONOPTIMIZE=1`. And it's a recent issue, the import works with `scikit-image-0.25.0`. 

### Way to reproduce:

```
PYTHONOPTIMIZE=2 python -c "from skimage.transform import resize"
```
Output:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from skimage.transform import resize
ImportError: cannot import name 'resize' from 'skimage.transform' (/opt/conda/lib/python3.13/site-packages/skimage/transform/__init__.py)
```

### Version information:

```Shell
3.13.12 | packaged by conda-forge | (main, Feb  5 2026, 05:53:46) [GCC 14.3.0]
Linux-6.18.7-76061807-generic-x86_64-with-glibc2.39
scikit-image version: 0.26.0
numpy version: 2.4.2
```
